### ISSUE TITLE
how to give inputs for model prediction

### ISSUE THREAD

**Issue by madhuvaani** [Deep1994/An-Attentive-Neural-Model-for-labeling-Adverse-Drug-Reactions#1]
Can you tell me how to Save and Load the Model, and give inputs for prediction?

**Comment by Deep1994** [comment]
Hi,  madhuvaani, sorry for the late reply. 
You can set the checkpoint to save your model via:

`filepath = './saved_models/weights-improvement-{epoch:02d}-{val_loss:.5f}.hdf5'
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_loss', verbose=1,
                                                    save_best_only=True, mode='auto')`

This code shoud be put below the model.compile()

And After the training process done, you should rebuild the structure of the model but no need to retrain it, then you can load the model via:

`model.load_weights("./saved_models/weights-improvement-05-0.87600.hdf5")`

You should specify the saved path by your own.

The input is combined with two parts, they are the word embeddings and character embeddings. The input shape looks like [batch_size, word_input, char_input], where word_input's shape is [batch_size, max_sentence_length], and char_input's shape is [batch_size, max_sentence_length, max_word_length].

I hope this can help you, let me know if you still have any question about my code, best wishes!
